---
    - name: install MySQL database
      apt: name={{ item }} state=present
      with_items:
        - default-mysql-server
        - default-mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create application database
      mysql_db: name={{ db_name }} state=present

    - name: create database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        state: present


